sudo: required

language: node_js

node_js:
  - 10

cache:
  directories:
    - "$HOME/.npm"
    - "$HOME/.cache"

install:
  - npm ci
  - npm build

before_script:
  - ./node_modules/.bin/http-server -p 8080 ./ --silent &

script:
  - npm run lint
  - npm run test
