sudo: false

language: node_js

node_js:
  - 10

cache:
  directories:
    - "$HOME/.npm"
    - "$HOME/.cache"

install:
  - npm ci
  - npm build

before_script:
  - npm run start

script:
  - npm run lint
  - npm run test
