sudo: required

language: node_js

node_js:
  - 10

addons:
  apt:
    packages:
      - libgconf-2-4    # required for cypress

cache:
  npm: true
  directories:
    - "$HOME/.cache"

install:
  - npm ci
  - npm run build

before_script:
  - ./node_modules/.bin/http-server -p 8080 ./ --silent &

script:
  - npm run lint
  - cypress run --record --key $CYPRESS_KEY
